shuffle = true
use_nerdfont = true
flip_status_indicators = true
audio_cache_size = 2048
library_tabs = ["playlists", "browse", "podcasts"]
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"q" = "focus queue"
"Shift+q" = "quit"
"a" = "queue"
"c" = "clear"
"Space" = "playpause"
"p" = "focus library"
"g" = "move top"
"Shift+g" = "move bottom"
"Shift+r" = "reconnect"

[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
