"MY VIMRC

"""" Auto Install Vim-Plug """"
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
				\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"""" Plugins """"
call plug#begin('~/.vim/plugged')

Plug 'junegunn/goyo.vim'
Plug 'dracula/vim',{'as':'dracula'}
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
"Plug 'bling/vim-bufferline'
Plug 'ajh17/VimCompletesMe'

call plug#end()


"""" General settings """"
	let mapleader =" "
	set nocompatible
	set number
	set relativenumber
	set encoding=utf-8
"	syntax on
	set showcmd
	set autoindent
	set backupdir-=.
	set backupdir=~/tmp,/tmp

	set tabstop=4
	set shiftwidth=4
	set expandtab

"""" Plugin Settings """"
" Goyo
	map <leader>g :Goyo<CR>

" vim-airline

" nerdtree
	map <leader>f :NERDTreeToggle<CR>
" bufferline
"	let g:bufferline_echo = 1



" Enable autocomplete
	set wildmode=longest,list,full
" Disable automatic commenting on newline
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Split navigation
	set splitbelow splitright
	map <C-h> <C-w>h
	map <C-j> <C-w>j
	map <C-k> <C-w>k
	map <C-l> <C-w>l
	map <C-p> <C-w>>
	map <C-u> <C-w><
	map <C-i> <C-w>-
	map <C-o> <C-w>+

	map <leader>c :!~/.scripts/compile % pwd<CR>
	map <leader>r :!~/.scripts/run % pwd<CR>
	map <leader>o :!~/.scripts/opener <c-r>%<CR><CR>
